name: CD

on:
  workflow_run:
    workflows: ["Django CI"]  # le nom du workflow dans ci.yaml
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull and restart Django 
        uses: appleboy/ssh-action@v1.0.3 #action to execute SSH commands on remote server
  
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/proj 
            set -a
            source /etc/proj.env
            set +a
            echo "DATABASE_URL is set:>>> ${DATABASE_URL} <<<"
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            # python manage.py collectstatic --noinput
            sudo systemctl restart proj
            sleep 2
            exit 0
