name: CD

on:
  workflow_run:
    workflows: ["Django CI"]  # le nom du workflow dans ci.yaml
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER:  ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD:  ${{ secrets.POSTGRES_PASSWORD }}
        

    steps:
      - name: Pull and restart Django 
        uses: appleboy/ssh-action@v1.0.3 #action to execute SSH commands on remote server
  
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            export DATABASE_URL="postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}"
            cd /home/ubuntu/proj 
            echo "DATABASE_URL is set:>>> ${DATABASE_URL} <<<"
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            # python manage.py collectstatic --noinput
            pkill -f "manage.py runserver" || true
            nohup python manage.py runserver 0.0.0.0:8000 &
            sleep 2
            echo "Django server restarted with nohup"
            exit 0

